language: go

matrix:
  include:
    - go: 1.9.4
    - go: 1.10.0
    - go: tip
  allow_failures:
    - go: tip

before_install:
  - curl https://glide.sh/get | sh

script:
  - make build
  - make coverage
  - make vet
  - make lint
